### PR TITLE
add npm test

### PR DESCRIPTION
**Pull request by pascalgrimaud**
related to https://github.com/stormpath/generator-jhipster-stormpath/issues/4

I generated a project with the .yo-rc.json from test/
Then, I copy all pom.xml, bower.json, all src/ into test/templates/default
Not sure all files are needed, only the files the stormpath generator changes because here, there is a lot lot lot files -> as I didn't have a lot of time, I didn't sort them, I put them all

@mraible : don't hesitate to take my code, close this PR and sort the files needed!

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Here the result you should see:

```
╭─pgrimaud@pgrxps  ~/projects/stormpath/generator-jhipster-stormpath  ‹npm-test› 
╰─$ npm test

> generator-jhipster-stormpath@0.0.1 test /home/pgrimaud/projects/stormpath/generator-jhipster-stormpath
> mocha test/*



  JHipster generator Stormpath
    Automated build
      ✓ generates stormpath.config.js file
      ✓ stormpath lib inside pom.xml
      ✓ stormpath lib inside bower.json


  3 passing (385ms)
```

**Comment by mraible** [comment]
Thanks @pascalgrimaud! I think it's good to have the whole project in test/templates/default. That way, I can use the jhipster:upgrade subgenerator to update it when I need to.

**Comment by mraible** [comment]
BTW, what's the difference between `npm test` and `gulp test`? The first one works, but the second doesn't seem to.

```
$ gulp test
[07:04:38] Using gulpfile ~/dev/generator-jhipster-stormpath/gulpfile.js
[07:04:38] Starting 'pre-test'...
[07:04:39] Finished 'pre-test' after 97 ms
[07:04:39] Starting 'test'...
```

**Comment by pascalgrimaud** [comment]
`gulp test` should display the test coverage
But for your module, it displays nothing! I don't know why.

Can you try my module ?
- git clone https://github.com/pascalgrimaud/generator-jhipster-docker.git
- npm install
- gulp test

That's what I got with my module:

```
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 app/      |    48.82 |    32.79 |       85 |    48.36 |                |
  index.js |    48.82 |    32.79 |       85 |    48.36 |... 276,277,279 |
-----------|----------|----------|----------|----------|----------------|
All files  |    48.82 |    32.79 |       85 |    48.36 |                |
-----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 48.82% ( 62/127 )
Branches     : 32.79% ( 20/61 )
Functions    : 85% ( 17/20 )
Lines        : 48.36% ( 59/122 )
================================================================================
[15:34:18] Finished 'test' after 983 ms
```

**Comment by mraible** [comment]
Strange, it worked yesterday! I tried your module and it works fine.

**Comment by mraible** [comment]
I added a console.log to the `test` task and now I see the problem:

```
err { [Error: Cannot find module 'protractor-jasmine2-screenshot-reporter']
  code: 'MODULE_NOT_FOUND',
  name: 'Error',
  message: 'Cannot find module \'protractor-jasmine2-screenshot-reporter\'',
  stack: 'Error: Cannot find module \'protractor-jasmine2-screenshot-reporter\'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.Module._load (module.js:276:25)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster-stormpath/test/templates/default/src/test/javascript/protractor.conf.js:3:32)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Object.Module._extensions.(anonymous function) [as .js] (/Users/mraible/dev/generator-jhipster-stormpath/node_modules/istanbul/lib/hook.js:109:37)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)',
  showStack: true,
  showProperties: true,
  plugin: 'gulp-mocha' }
```

**Comment by mraible** [comment]
If I remove `test/templates/default/src/test/javascript/protractor.conf.js`, I get a new error about Angular missing.

```
err { [ReferenceError: angular is not defined]
  name: 'ReferenceError',
  message: 'angular is not defined',
  stack: 'ReferenceError: angular is not defined\n    at /Users/mraible/dev/generator-jhipster-stormpath/test/templates/default/src/main/webapp/app/app.constants.js:4:5\n    at Object.<anonymous> (/Users/mraible/dev/generator-jhipster-stormpath/test/templates/default/src/main/webapp/app/app.constants.js:8:3)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Object.Module._extensions.(anonymous function) [as .js] (/Users/mraible/dev/generator-jhipster-stormpath/node_modules/istanbul/lib/hook.js:109:37)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at /Users/mraible/dev/generator-jhipster-stormpath/node_modules/gulp-mocha/node_modules/mocha/lib/mocha.js:220:27',
  showStack: true,
  showProperties: true,
  plugin: 'gulp-mocha' }
```

It's almost like `gulp test` is doing a compilation of sorts, whereas `npm test` is not.

**Comment by mraible** [comment]
I figured it out, gulp was trying to run all the js files. Here's the fix: https://github.com/stormpath/generator-jhipster-stormpath/commit/a1714cadc8e34e93b57a6da8a05672e68a7f45fa

**Comment by pascalgrimaud** [comment]
oh yes, you're right !!!
good catch

**Pull request merged**
